config/routes.rb
Rails.application.routes.draw do
  resources :todo_lists do
    resources :todo_items
  end
  
  devise_for :users
  root to: "todo_lists#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :todo_list
end

app/models/todo_item.rb
class TodoItem < ApplicationRecord
  belongs_to :todo_list
  # Only creates a todo-item if the description exists
  validates :description, presence: { message: "Description can't be blank" }

  enum status: { open: 0, closed: 5 }
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
  belongs_to :user
  has_many :todo_items, dependent: :destroy
  accepts_nested_attributes_for :todo_items, allow_destroy: true, reject_if: proc { |attributes| attributes['description'].blank? }
  enum status: { personal: 0, shareable: 5 }
  validates :name, presence: { message: "Name can't be blank" }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  has_many :todo_lists, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :name, presence: { message: "Name can't be blank" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  # Mostra todas as listas definidas como 'favoritas'
  def index 
    @favorites = current_user.favorites.map(&:todo_list)
  end

  # Uusário pode favoritar uma lista
  def create
    @favorite = Favorite.create(todo_list_id: params[:todo_list_id])
    @favorite.user = current_user
    @favorite.save
    flash[:notice] = "'#{@todo_list.name}' marked as favorite"
    redirect_to todo_list_path(@favorite.todo_list)
  end

  # Uusário pode desmarcar uma lista, a lista irá voltar à pagina inicial com o 'redirect_back'
  def destroy
    @favorite = Favorite.find_by(todo_list_id: params[:todo_list_id], user_id: current_user.id)
    @favorite.destroy
    flash[:notice] = "#{@todo_list.name} 'unmarked as favorite'"
    redirect_back(fallback_location: todo_list_path(params[:todo_list_id]))
  end
end

app/controllers/todo_items_controller.rb
class TasksController < ApplicationController
  # Permite mudar o status de uma tarefa para feita
  def set_it_done
    @todo_item = TodoItem.find(params[:todo_item_id])
    @todo_item.update(status: :closed)
    flash[:notice] = "'#{todo_item.description}' marked as done"
    redirect_to todo_list_path(@todo_item.todo_list)
  end

  # Permite mudar o status de uma tarefa para não feita
  def set_it_undone
    @todo_item = TodoItem.find(params[:todo_item_id])
    @todo_item.update(status: :open)
    flash[:notice] = "'#{todo_item.description}' marked as undone"
    redirect_to todo_list_path(@todo_item.todo_list)
  end

  # Permite deletar um item específico
  def destroy
    @todo_item = TodoItem.find(params[:id])
    @todo_item.destroy
    redirect_to edit_todo_list_path(params[:todo_list_id])
  end
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :locate_favorites, only: [:show, :locate]
  before_action :set_todo_list, only: [:update, :destroy]
  before_action :set_todo_list_id, only: [:create_todo_item, :make_it_public, :make_it_private]
  
  def index
    # Mostra as listas criadas na order decrescente
    @todo_lists = current_user.todo_lists.order(created_at: :desc)
  end
  
  def show
    if !check_access?
      flash[:alert] = "You don't have access to this list"
      redirect_to root_path
    else
      return @todo_list, @favorites_ids
    end
  end
  
  # No momento da criação de uma lista, o usuário pode criar divernos itens(tarefas) para essa lista
  def new
    @todo_list = TodoList.new
    @todo_list.todo_items.build
  end
  
  
  def create
    @todo_list = TodoList.new(todo_list_params)
    @todo_list.user = current_user
    if @todo_list.save
      flash[:notice] = 'To-do list was created'
      redirect_to todo_lists_path
    else
      render :new
    end
  end

  # Verifica o acesso do usuário antes de editar uma lista
  def edit
    if !check_access?
      flash[:notice] = "You don't have access to this list"
      redirect_to root_path
    end
  end
  
  def update
    if @todo_list.update(todo_list_params)
      redirect_to todo_lists_path
    else
      render :edit
    end
  end

  # Torna uma determinada lista privada
  def make_it_private
    @todo_list.update(status: :personal)
    flash[:notice] = "'#{@todo_list.name}' is now private"
    redirect_to todo_list_path(@todo_list)
  end

  # Torna uma determinada lista publica
  def make_it_public
    @todo_list.update(status: :shareable)
    flash[:notice] = "'#{@todo_list.name}' is now public"
    redirect_to todo_list_path(@todo_list)
  end
  
  def destroy
    if @todo_list.destroy
      redirect_to todo_lists_url
    end
  end

  # Cria tarefas
  def create_todo_item
    @todo_list.update(todo_list_params)
    redirect_to @todo_list
  end

  def locate
    @todo_lists = TodoList.where(status: :shareable).where.not(user_id: current_user.id).order(created_at: :desc)
  end
  
  private

  # Verifica se o usuário tem direito de acesso à lista
  def check_access
    @todo_list = TodoList.find(params[:id])
    # Verifica se o usuário é o dono da lista(terá acesso pois é o criador) ou verifica se a lista é pública, desta maneira qualquer usuário terá acesso
    (@todo_list.user == current_user || @todo_list.shareable?) ? true : false
  end

  def locate_favorites
    # Passa um bloco como argumento e usa dentro dentro do método
    @favorites = current_user.favorites.map(&:todo_list)
    @favorites_ids = []
    @favorites.each { |item| @favorites_ids << item.id }
    return @favorites_ids
  end

  def set_todo_list
    @todo_list = TodoList.find(params[:id])
  end
  
  # Permite apenas parametros confiaveis passar
  def todo_list_params
    params.require(:todo_list).permit(:name, task_items_attributes: [:id, :description])
  end

  def set_todo_list_id 
    @todo_list = TodoList.find(params[:todo_list_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Your Task</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
  <header class="header">
    <a href="/" class="logo">
      <h1>Task.io</h1>
    </a>
    <nav>
      <ul class="nav_list">
        <li>
          <a href="">Favorites</a>
        </li>
        <li>
          <a href="">Private Lists</a>
        </li>
        <li>
        <%= link_to destroy_user_session_path, method: :delete do %>
          <i class="fas fa-sign-out-alt"></i>
        <% end %>
        </li>
        <!-- <ul class="aside_list-item"></ul> -->
      </ul>
    </nav>
  </header>

app/views/todo_items/_form.html.erb
<%= form_for([@todo_item.todo_list, @todo_item]) do |f| %>
  <% if @todo_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo_item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @todo_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :status %>
    <%= f.select :status, Todo_Item::STATUS_OPTIONS, {} %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/todo_items/edit.html.erb
<%= link_to "Back", @todo_list %>
<div class="card">
  <div class="card-body">
    <h2 class='card-title'>
      <span>Editing task</span>
    </h2>
    <%= render 'form' %>
  </div>
</div>

app/views/todo_items/index.html.erb
<h1>Listing tasks</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Status</th>
    <th>Project</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @todo_items.each do |todo_item| %>
  <tr>
    <td><%= todo_item.name %></td>
    <td><%= todo_item.description %></td>
    <td><%= todo_item.status %></td>
    <td><%= todo_item.todo_list %></td>
    <td><%= link_to 'Show', [todo_item.todo_list, todo_item] %></td>
    <td><%= link_to 'Edit', edit_todo_list_todo_item_path(todo_item.todo_list, todo_item) %></td>
    <td><%= link_to 'Destroy', [todo_item.todo_list, todo_item], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Task', new_todo_list_task_path(params[:todo_list_id]) %>

app/views/todo_items/new.html.erb
<h1>New Task</h1>

<%= render 'form' %>

<%= link_to "Back", todo_lists_path(@todo_item.todo_list) %>

app/views/todo_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @todo_item.name %>
</p>

<p>
  <b>Description:</b>
  <%= @todo_item.description %>
</p>

<p>
  <b>Status:</b>
  <%= @todo_item.status %>
</p>

<p>
  <b>Project:</b>
  <%= @todo_item.todo_list %>
</p>


<%= link_to 'Edit', edit_todo_list_todo_item_path(@todo_item.todo_list, @todo_item) %> |
<%= link_to 'Back', todo_list_todo_items_path(@todo_item.todo_list) %>

app/views/todo_lists/_form.html.erb
<%= form_with(model: todo_list, local: true) do |form| %>
  <% if todo_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todo_list.errors.count, "error") %> prohibited this todo_list from being saved:</h2>

      <ul>
        <% todo_list.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/todo_lists/edit.html.erb
<h1>Editing Todo List</h1>

<%= render 'form', todo_list: @todo_list %>

<%= link_to 'Show', @todo_list %> |
<%= link_to 'Back', todo_lists_path %>

app/views/todo_lists/index.html.erb
<!-- Grid Warpper -->
<p id="notice"><%= notice %></p>

<div class="grid-container">
  <%= render 'shared/navbar' %>

  <section class="create_new">
    <h1>Hello User</h1>
    <%= link_to 'New Todo List', new_todo_list_path, :class => "new_task-btn" %>
  </section>

  <!-- Main Sewction -->
  <main class="main">
    <% @todo_lists.each do |todo_list| %>
    <div class="card-container">
      <div class="card-item">
        <div class="intro">
          <h2><%= todo_list.name %></h2>
        </div>
        <p class="description"><%= todo_list.description %></p>
        <div class="card-info">
          <%= link_to todo_list do %>
            <i class="far fa-eye"></i>
          <% end %> 
          <%= link_to edit_todo_list_path(todo_list) do %>
            <i class="far fa-edit"></i>
          <% end %> 
          <%= link_to todo_list, method: :delete, data: { confirm:
          'Are you sure?' } do %>
            <i class="far fa-trash-alt"></i>
          <% end %>
        </div>
      </div>
    </div>
    <% end %>
  </main>
</div>

app/views/todo_lists/new.html.erb
<h1>New Todo List</h1>

<%= render 'form', todo_list: @todo_list %>

<%= link_to 'Back', todo_lists_path %>